#!/bin/bash

#Hello everyone gutten morgen xd
set +xv #mute toomany arguments
#http://bhfsteve.blogspot.com/2014/07/embedding-python-in-bash-scripts.html


export zygotePID=$$


killzygote(){
busybox pkill -P $zygotePID
}

bot_engine_main(){
PYTHON_ARG="$1" python - <<END
import os
from chatterbot import ChatBot
chatbot = ChatBot("TakoAI")
input = os.environ['PYTHON_ARG']
response = chatbot.get_response(input)
print(response)
END
}

#Colouring Functions
red(){
printf '\e[38;5;210m ' > /dev/tty
}

yellow(){
printf '\e[38;5;221m ' > /dev/tty
}
green(){
printf '\e[38;5;042m ' > /dev/tty
}
blue(){
printf '\e[38;5;039m ' > /dev/tty
}

#color
bot_command_spitter(){
${output} &>> ${currdir}/logs/botsystemPrompt
}

killall_bgsvc(){
processlist=$(cat ${currdir}/memory/bgproc)
for a in ${processlist}; do
kill -9 ${a}
done
kill -9 ${memmanagerid}
rm -rf ${currdir}/memory/bgproc
}

suspend_bgsvc(){
processlist=$(cat ${currdir}/memory/bgproc)
yellow
echo All process has been suspended
for a in ${processlist}; do
kill -19 ${a}
done
}

resume_bgsvc(){
processlist=$(cat ${currdir}/memory/bgproc)
green
echo All process has been resumed
for a in ${processlist}; do
kill -18 ${a}
done
} 

memoryUsage(){
Usage=$(free | grep Mem | awk '{print $3/$2 * 100.0}')
Usage=$( printf "%.0f" $(echo ${Usage}))
echo "$Usage"
}



memorymanagement(){
export MMBADGE="[MemoryManagement]"
yellow
echo "$MMBADGE Memory Management Started up" > /dev/tty
while true ; do
memoryUsage
echo "Memory Usage $Usage"
if [ $Usage -gt "80" ] ;then
red
echo "$MMBADGE Memory Deprivation Detected"
echo "$MMBADGE To prevent further memory corruption The execution will stop until Enough memory"
suspend_bgsvc
while [ "$Usage" -gt "80" ] ; do
memoryUsage
sleep 2
done
resume_bgsvc
fi
sleep 0.2
done
}

bot_learnseq_engine(){
for a in ${currdir}/NN/* ; do
cat ${a}
echo ${a}
export PYTHON_ARG=${a}
PYTHON_ARG="${a}" python - << END
import os
from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot

chatbot = ChatBot("TakoAI")
LearnFILE = os.environ['PYTHON_ARG']
conversation = (LearnFILE, 'r')
print(conversation)
trainer = ListTrainer(chatbot)
trainer.train(conversation)
END
done
}


#Porting for q7OS
export currdir=$(pwd)
export HOME=${currdir}/FetchedData
mkdir FetchedData
cd ${currdir}
export LD_PRELOAD=

#bb

folderinit(){
mkdir ${currdir}/extra_modules
mkdir ${currdir}/memory
mkdir ${currdir}/logs
mkdir ${currdir}/sensedata
if [ ! -f InteractionReinforcement ]; then
mkdir ${currdir}/NN
echo a >> ${currdir}/NN/InteractionReinforcement
fi
}


logorender(){
red
echo "  ____      __       ___   ____";
echo " / __ \____/ /____  / _ | /  _/";
green
echo "/ /_/ / __/ __/ _ \/ __ |_/ /  ";
blue
echo "\____/\__/\__/\___/_/ |_/___/  ";
echo "                               ";

}

#############################BOOT SERVICES CALL #########################################

svcStart(){
echo Starting customized Daemon and Drivers
daemonLoad &> ${currdir}/logs/inputbinlogs
echo $! >> ${currdir}/memory/bgproc
echo Starting dataInput Translator
anyInputtoBinary &> ${currdir}/logs/inputbinlogs.log &
echo $! >> ${currdir}/memory/bgproc
memorymanagement &> ${currdir}/logs/mmmanage.log &
memmanagerid=$(echo $!) 
}

##############################CUSTOM DAEMONS OR DRIVER LOADER#############################

daemonLoad(){
for i in ${currdir}/extra_modules/* ; do
echo $i
bash ${i} &
echo $! >> ${currdir}/memory/bgproc
done
}



###############################MainSENSORYBINARYDECODER###############################

anyInputtoBinary(){
for a in ${currdir}/senseData/* ; do
xxd -ps ${a} > ${currdir}/NN/${a}_raw
done
}

###############################BASIC AI TEXT INPUT OUTPUT#############################3


export USERUI="User > "
export BOTUI="octo > "

bot_fetch_web_engine(){
if [ ! -f ${currdir}/memory/webspiderlock ]; then
sh $0 "${inputtxt}" 
fi
}


botmainChat(){
if [ -z $output ] ;then
output=aaaa
fi
while true ; do
#inputtxt=$(dialog --title "Chat" --inputbox "Please Enter Your Message" 8 40 2>&1 >/dev/tty)
green
echo -n "${USERUI}"
read inputtxt
exit_input
#dialog --infobox Processing 5 50
if [ ! -z "${inputtxt}" ] ; then 
botChatReply &> /dev/null &
echo $! >> ${currdir}/memory/bgproc
fi
#dialog --title "OctopusAI" --msgbox "${output}" 5 50
done
}

botChatReply(){
if [ ! -z "${inputtxt}" ] ;then 
echo "${inputtxt}" >> ${currdir}/NN/InteractionReinforcement
output=$(bot_engine_main "${inputtxt}") 2>&1 >> ${currdir}/logs/NNlog.log &> /dev/null
bot_learnseq_engine &>> ${currdir}/logs/NNlog.log &
echo $! >> ${currdir}/memory/bgproc
bot_fetch_web_engine &>> ${currdir}/logs/webcrawler.log &
echo $! >> ${currdir}/memory/bgproccc
if [ ! -z ${output} ] && [ ${output} != 'r' ] ;then
echo "${output}" >> ${currdir}/NN/InteractionReinforcement
echo ${blank} > /dev/tty
bot_command_spitter
blue > /dev/tty
echo "${BOTUI} ${output}" > /dev/tty
green > /dev/tty
echo -n "${USERUI} " > /dev/tty
fi
fi
}


#################################BASIC IO AI END############################
dependencies(){
while true ; do
pacman -S lynx httrack busybox dialog python python-setuptools coreutils --noconfirm --needed
apt-get -y install lynx httrack busybox dialog python3 python3-setuptools
easy_install pip
pip install chatterbot_corpus
pip install conda
pip install cytoolz
python -m conda install -y python-dateutil
python -m conda install -y spacy
python -m conda install -y pint
python -m conda install -y pymongo
python -m conda install -y pyyaml
python -m conda install -y pytz
python -m conda install -y mathpase
python -m conda install -y sqlalchemy
pip install pyyaml
pip install sumy
pip install chatterbot 
python -c "import nltk; nltk.download('punkt')" 
done
}

exit_input(){
if [ "${inputtxt}" == 'exit' ] ;then
killall_bgsvc
killzygote
exit
fi
}

#forMemoryModuleLoader

load_mem(){
file=$1
export filelist="${filelist} ${file}" > /dev/null 2>&1
export memstore_${file}="$(cat ${file})" > /dev/null 2>&1
rm -f ${file}.mem
}

download_mem(){
file=$1
destoffload=$2
if [ ! -z "$destoffload" ] && [ ! -z "$memstore_${file}" ] ; then
echo "$memstore_${file}" > "${destoffload}"
fi

}

discard_mem(){
file=$1
export memstore_${file}= > /dev/null 2>&1
}

discard_all_mem(){
for a in ${filelist}; do
export memstore_${a}=
done
export filelist=
}

load_mem_recursive(){
filelist=$(find "${dir}")
for i in ${filelist}; do
load_mem "$i"
done
}




#################################MAIN INIT AI LOGIC##############################

#MAIN
#start Main Module
folderinit
dependencies &> ${currdir}/logs/dependenciesinst.log &
echo $! >> ${currdir}/memory/bgproc
clear
green
echo Welcome to OctopusAI created by questandachievement7Developers
logorender
svcStart
if [ -z $1 ] ;then
botmainChat
fi


#############################MAIN PROGRAM ENDED ############################################################
#############################WEB SPIDER PARTITION DO NOT WRAP IT AS FUNCTION####################################
echo aa > ${currdir}/memory/webspiderlock #lock webspider so it doesnt launch more causes CPU bottleneck

MemoryTotal=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
memdefine=$(( ( $MemoryTotal / 1 ) / 1024 ))
memsize="${memdefine}M"
Boostlimit=$(( $memdefine * 100 / 64000 ))
echo DEBUG Learn Boost limit $Boostlimit memorydetected $memsize
if [ -z "$1" ]; then
  echo if you want to search data do
  echo '$ ./ThisBinaryName search'
 #exit
fi

kocheng=$1
SEARCH=$1
#set -x
cd $(pwd)
#pip install sumy > /dev/null 2>&1 &
#python -c "import nltk; nltk.download('punkt')" > /dev/null 2>&1 &

currdir=$(pwd)
echo This is the directory $(pwd)
echo loading...
#find . -iname "*tmp*"
echo 2nd async pass load
#find . -iname "*tmp*" -exec rename .tmp.html .html '{}' \;
find ${currdir} -name "*tmp*" -exec bash -c 'mv "$1" "${1%.tmp}"' - '{}' \; > /dev/null 2>&1 &
echo Loading
chmod 777 -R .


#rm -rf web
if [ ! -d cachefile ]; then
  mkdir cachefile
  #mount -t tmpfs -o size=512M tmpfs cachefile
fi



exta='aif cda mid mp3 mpa ogg wav wma wpl 7z arj deb pkg rar rpm tar.gz z zip bin dmg iso toast vcd csv dat db dbf log mdb sav  sql tar xml apk bat bin cgi pl com exe gadget jar py wsf fnt fon otf ttf ai bmp gid ico jpeg jpg png ps psd svg tif asp cer cfm cgi css htm js jsp part php py rss xhtml c class cpp cs h java sh swift vb ods xlr xls bak cab cfg cpl cur dll dmp drv icns ico ini 3g avi flv h264 m4v mkv mov mp4 mpeg mpg rm swf vob wmv doc odt pdf rtf tex txt wks wps wpd'
Documents='xls doc pdf ppt wps txt rtf sql html css htm'
mkdir ${HOME}
for ext in $Documents; do
mkdir "${HOME}/Documents"
chmod -R 777 "${HOME}/Documents"
find "cachefile" -name "*.*$ext*"
find "cachefile" -name "*.*$ext*" | while read file; do
    mv -v "$file" "${HOME}/Documents"; done
done
Archive='rar rpm tar.gz z zip bin dmg iso 7z arj'
mkdir ${HOME}
for ext in $Archive; do
mkdir "${HOME}/Archive"
chmod -R 777 "${HOME}/Archive"
find "cachefile" -name "*.*$ext*"
find "cachefile" -name "*.*$ext*" | while read file; do
    mv -v "$file" "${HOME}/Archive"; done
done
Audio='aif cda mid mp3 mpa ogg wav wma'
mkdir ${HOME}
for ext in $Audio; do
mkdir "${HOME}/Audio"
chmod -R 777 "${HOME}/Audio"
find "cachefile" -name "*.*$ext*"
find "cachefile" -name "*.*$ext*" | while read file; do
    mv -v "$file" "${HOME}/Audio"; done
done

Video='3g avi flv h264 m4v mkv mov mp4 mpeg mpg rm swf vob wmv'
mkdir ${HOME}
for ext in $Video; do
mkdir "${HOME}/Video"
chmod -R 777 "${HOME}/Video"
find "cachefile" -name "*.*$ext*"
find "cachefile" -name "*.*$ext*" | while read file; do
    mv -v "$file" "${HOME}/Video"; done
done

Picture='ai bmp gid ico jpeg jpg png ps psd svg tif'
mkdir ${HOME}
for ext in $Video; do
mkdir "${HOME}/Picture"
chmod -R 777 "${HOME}/Picture"
find "cachefile" -name "*.*$ext*"
find "cachefile" -name "*.*$ext*" | while read file; do
    mv -v "$file" "${HOME}/Picture"; done
done


if [ $kocheng == 'search' ]; then
search=$(dialog --title "search" --inputbox "request any type of fetched data" 8 40 2>&1 >/dev/tty)
clear
if [ $search == 'debug' ]; then
  echo Debugging mode enabled
  tail -f bgfetch
  exit
fi
echo Loading...
echo This loading may take long if you have run $0 for a long time
#list=$(cd / ; grep -ril ${currdir}/${HOME} -e "${search}")
list=$(cd / ; grep -ril ${HOME} -e "${search}")
echo what
listhtml=$( grep -ril --include \*.html ${HOME}/Documents -e "${search}" )
#listhtml=$( grep -ril --include \*.html ${currdir}/${HOME}/Documents -e "${search}" )
echo $list
echo $listhtml
sleep 4
if [ -z "$list" ]; then
 echo Content is not found Fetching in the background
 echo Data EXPUNGED
 sleep 1
 echo Fixing Data inconsistencies
 echo 'note: try to search something else'
 sleep 5
 sh $0 $search 
else
  clear
echo Indexed Data Found
echo $listhtml
sleep 4
grep -rnw . -e "${search}" > garbled_${search}
mkdir ReinforcedLearning
#Sumary all the things
clear
echo Learning Text
counttotal=0
for a in $listhtml; do
  counttotal=$(( $counttotal + 1 ))
done
count=0
learnboost="learnboost is activated"
for a in $listhtml; do
  count=$(( $count + 1 ))
  percent=$(( $count * 100 / $counttotal ))

  #sumy edmundson --length=4 --file=2-hari-lagi-yamaha-siap-luncurkan-skuter-hybrid.html  --format=html
  if [ $percent -lt ${Boostlimit} ]; then
  echo Reserving Resources for boostmode $Boostlimit of the process only
  sumy edmundson --length=4 --file=${a} --format=html >> ${currdir}/ReinforcedLearning/CompiledInformation_${search} &
    else
  learnboost="learnboost is disabled"
  dialog --title "Neural Learning Data Mining" --gauge "Learning and Creating Answer about ${search} Topic" 7 70 ${percent} &
  echo Processor Load $CPU
  if [ $(( $percent % 6 )) == 0 ] ;then
  free
  CPU=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage ""}')
fi
  sumy edmundson --length=4 --file=${a} --format=html >> ${currdir}/ReinforcedLearning/CompiledInformation_${search}
fi
done
result=$(sumy edmundson --length=2 --file="${currdir}/ReinforcedLearning/CompiledInformation_${search}")
echo MUST FAIL
sleep 5
echo "${result}" > ${currdir}/ReinforcedLearning/result_${search}
 killall -KILL wget firefox
for i in ${list} ; do
  echo ${i}
 #firefox -new-tab "file://${i}" 2>&1  &
 sleep 0
done
cat "ReinforcedLearning/result_${search}" >> ${currdir}/NN/InteractionReinforcement
fi
sh $0 search
exit
fi



dupefilelist=$(ls cachefile/cachefile)
for a in ${dupefilelist}; do
	rm -fv "cachefile/*$a*"
	echo cleaning duplicates $a
done
#rm -rf
#Sorting machine
#exta='aif cda mid mp3 mpa ogg wav wma wpl 7z arj deb pkg rar rpm tar.gz z zip bin dmg iso toast vcd csv dat db dbf log mdb sav  sql tar xml apk bat bin cgi pl com exe gadget jar py wsf fnt fon otf ttf ai bmp gid ico jpeg jpg png ps psd svg tif asp cer cfm cgi css htm js jsp part php py rss xhtml c class cpp cs h java sh swift vb ods xlr xls bak cab cfg cpl cur dll dmp drv icns ico ini 3g avi flv h264 m4v mkv mov mp4 mpeg mpg rm swf vob wmv doc odt pdf rtf tex txt wks wps wpd'
exta='aif cda mid mp3 mpa ogg wav wma wpl 7z arj deb pkg rar rpm tar.gz z zip bin dmg iso toast vcd csv dat db dbf log mdb sav  sql tar xml apk bat bin cgi pl com exe gadget jar py wsf fnt fon otf ttf ai bmp gid ico jpeg jpg png ps psd svg tif asp cer cfm cgi css htm js jsp part php py rss xhtml c class cpp cs h java sh swift vb ods xlr xls bak cab cfg cpl cur dll dmp drv icns ico ini 3g avi flv h264 m4v mkv mov mp4 mpeg mpg rm swf vob wmv doc odt pdf rtf tex txt wks wps wpd'

#exta=$(dialog --title "FILE TYPE SELECTION" --inputbox "Type the filetype that you want to search for example (png jpeg) etc.." 8 40 2>&1 >/dev/tty)

#sleep 4
mkdir web
clear
echo ""
echo ".=========================================================."
echo "|                                                         |"
echo "|  Hybrid offlinecaching                                  |"
echo "|  ---------------------------------------------------    |"
echo "|                                                         |"
echo "|  Version: 1.0                                           |"
echo "|  Developed by: Rishi Narang                             |"
echo "|  Wrapped and modified by questandachievement7           |"
echo "|  Blog: www.wtfuzz.com                                   |"
echo "|                                                         |"
echo "|  Usage: ./gocmd.sh <search strings>                     |"
echo "|  Example: ./gocmd.sh example and test                   |"
echo "|                                                         |"
echo ".=========================================================."
echo ""


#sleep 2
if [ -z $1 ]
then
 echo "ERROR: No search Topic string supplied."
 echo "USAGE: webspider.sh <search srting>"
 echo ""
 SEARCH=$(dialog --title "Document digger" --inputbox "Search for what?" 8 40 2>&1 >/dev/tty)
 #echo -n "Anyways for now, supply the search string here: "
 #read SEARCH
else
 SEARCH=$@
fi

URL="http://google.com/search?hl=en&safe=off&q="
URL="https://duckduckgo.com/?q="
STRING=`echo $SEARCH | sed 's/ /%20/g'`
URI="$URL%22$STRING%22"
lynx -dump $URI > gone.tmp
sed 's/http/\^http/g' gone.tmp | tr -s "^" "\n" | grep http| sed 's/\ .*//g' > gtwo.tmp
#rm gone.tmp
sed '/google.com/d' gtwo.tmp > rawurlsstage0
sed '/duckduckgo.com/d' gtwo.tmp > rawurlsstage0

#because due to the port from google Call to duckduckgo call we have to reimplement Translation
echo Translation Debug
#sleep 4
sed 's/\%3A/:/g' rawurlsstage0 > rawurlsstage1
sed 's/\%2F/\//g' rawurlsstage1 > urls
#rm gtwo.tmp
listurl=$(wc -l urls)
if [ $listurl == '0 urls' ]; then
echo something went wrong
dialog --title "webspider" --msgbox "cannot retrieve any data at the moment" 5 50 > /dev/tty
exit
fi
echo "SUCCESS: Extracted `wc -l urls` and listed them in '`pwd`/urls'
file for reference."
echo ""
#cat urls
echo ""
search=$(cat urls)
echo $search
#sleep 1
#EOF
#recoll -q "$SEARCH" &
mkdir "$(pwd)/cachefile/${SEARCH}"
if [ ! -d "${currdir}/cachefile/${SEARCH}" ] ; then
echo Caching Failure
exit
fi

find cachefile -iname "*tmp*" -exec rename .tmp.html .html '{}' \; &
pwd
#cd "$(pwd)/cachefile/${SEARCH}"
echo $pwd
mkdir "$(pwd)/cachefile/${SEARCH}"
sleep 2
SEARCHONEWORD=$(echo $SEARCH | awk '{print $1;}')
echo $SEARCHONEWORD
pwd
echo dir
rm -rf ../${SEARCH}
#sleep 10
declare -A arr
shopt -s globstar

cd ..
sleep 0
#search=$(zenity --entry --text "Start Caching your website" );

#convertedbar=${search// /+}
exclude='"-*duckduckgo.com/assets/*" "-*duckduckgo.com/js/*" "-*duckduckgo.com/font/*" '
echo $convertedbar
sleep 0
echo "$search"
cd "$currdir"
mkdir "$(pwd)/cachefile/${SEARCH}/webcache"
if [ ! -d $(pwd)/cachefile/${SEARCH}/webcache ]; then
  echo It seems the program refuse to work at all
  echo Reason Directory was created and magically dissapear
  echo Or the actual working directory is magically moved to another place
  exit
fi
for link in $search ; do
for ext in $exta ;do
#httrack --continue "$link" -O "$(pwd)/cachefile/${SEARCH}/webcache" "+*.*.*/*.*" ${exclude} -v
cd "$currdir"
echo This is the directory $(pwd)
httrack --continue "$link" -O "$(pwd)/cachefile/${SEARCH}/webcache" "+*${SEARCHONEWORD}*${ext}*" ${exclude} -v
echo This is the directory $(pwd)
done
#pullfiles
for ext in $exta; do
mkdir "$(pwd)/cachefile/${SEARCH}/$ext"
chmod -R 777 "$(pwd)/cachefile/${SEARCH}/$ext"
find "$(pwd)/cachefile/${SEARCH}/webcache" -name "*.*$ext*"
find "$(pwd)/cachefile/${SEARCH}/webcache" -name "*.*$ext*" | while read file; do
    mv -v "$file" "$(pwd)/cachefile/${SEARCH}/$ext"; done
done
#rm -rf "$(pwd)/cachefile/${SEARCH}/webcache"
mkdir "$(pwd)/cachefile/${SEARCH}/webcache"
done
sleep 9
declare -A arr
shopt -s globstar
#dialog --title "Webspider" --msgbox "Cleaning files before starting cache" 5 50 &
rm ${currdir}/memory/webspiderlock #remove webspider lock
count=0
for file in **; do
  [[ -f "$file" ]] || continue

  read cksm _ < <(md5sum "$file")
  if ((arr[$cksm]++)); then
    echo "cleaning redundant web $count file"
    count=$(($count + 1))
  fi
done
cd ..
sleep 0

sleep 6000
#}



botmainChat
